#!/bin/bash

blockMesh 2>&1 | tee log.blockmesh

decomposePar -copyUniform -cellDist 2>&1 | tee log.decompose

mpirun -n 4 snappyHexMesh -overwrite -parallel 2>&1 | tee log.SHM

reconstructParMesh -constant 2>&1 | tee log.reconstruct
