#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh
cp 0/alpha.liquid.orig 0/alpha.liquid
cp 0/alpha.solid.orig 0/alpha.solid
cp 0/diffCo.orig 0/diffCo
cp 0/C.orig 0/C
runApplication setFields
runApplication $(getApplication)


#------------------------------------------------------------------------------
