#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh
cp 0/alpha.liquid.orig 0/alpha.liquid
cp 0/alpha.solid.orig 0/alpha.solid
runApplication setFields
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar

#------------------------------------------------------------------------------
